package space.cohub.vdp.protolake.util.git;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Git's {@code safe.directory} trust for the lake repository protolake works in.
 *
 * <p>Git 2.35.2 and later refuse a repository whose directory belongs to another user
 * ("detected dubious ownership"). A lake commonly does: protolake runs as uid 1001 in its
 * image, while a bind-mounted lake belongs to the host user, and Docker Desktop's VirtioFS
 * reports a mount's root as owned by root. Protolake trusts exactly the repository it was
 * pointed at, never a wildcard, the same exception actions/checkout makes for its workspace.
 * The trust lives in protolake rather than in the wrapper script, so lakes generated by an
 * older wrapper are covered without regenerating it.
 */
public final class SafeDirectory {

    private SafeDirectory() {}

    /**
     * {@code -c safe.directory=<path>} arguments that make one git invocation trust
     * {@code repository}'s worktree. Command-line configuration reaches only that git
     * process, which is all a direct invocation needs.
     */
    public static List<String> configArgs(Path repository) {
        List<String> args = new ArrayList<>();
        for (String name : names(repository)) {
            args.add("-c");
            args.add("safe.directory=" + name);
        }
        return args;
    }

    /**
     * Writes a temporary global git config that trusts {@code repository}'s {@code .git}
     * directory, for tools that clone the repository locally (buf's {@code .git#ref=}
     * inputs). The image's git, Ubuntu's 2.43 with the CVE-2024-32004 patch (upstream
     * reverted it in 2.45.2), refuses to serve a local clone of a git directory another
     * user owns, and git strips command-line configuration from the serving process, so
     * the trust must come from a global config. The file first includes the global config
     * files git would read for the cloning process, so the user's other settings still apply.
     *
     * @throws IOException if GIT_CONFIG_GLOBAL, HOME or XDG_CONFIG_HOME is a relative path
     *     (see {@link #userGlobalConfigs}), or the file cannot be written
     */
    public static CloneTrust trustForLocalClone(Path repository) throws IOException {
        return trustForLocalClone(repository, System.getenv());
    }

    /**
     * {@link #trustForLocalClone(Path)} for a cloning process that inherits {@code environment}
     * rather than this JVM's environment.
     */
    public static CloneTrust trustForLocalClone(Path repository, Map<String, String> environment)
            throws IOException {
        return trustForLocalClone(repository, userGlobalConfigs(environment));
    }

    static CloneTrust trustForLocalClone(Path repository, List<String> userConfigs) throws IOException {
        return trustForLocalClone(repository, userConfigs,
            (file, content) -> Files.writeString(file, content, StandardCharsets.UTF_8));
    }

    static CloneTrust trustForLocalClone(Path repository, List<String> userConfigs, ConfigWriter writer)
            throws IOException {
        StringBuilder config = new StringBuilder("[include]\n");
        for (String userConfig : userConfigs) {
            // Git skips a global config it may not read, but an include it may not read is
            // fatal to every git command, so only a readable file becomes an include.
            if (Files.isReadable(Path.of(userConfig))) {
                config.append("\tpath = ").append(quote(userConfig)).append('\n');
            }
        }
        // After the include: an empty safe.directory in the user's config clears the
        // entries before it, and must not clear this one.
        config.append("[safe]\n");
        for (String name : names(repository)) {
            config.append("\tdirectory = ").append(quote(name + "/.git")).append('\n');
        }
        Path file = Files.createTempFile("protolake-git-", ".gitconfig");
        try {
            writer.write(file, config.toString());
        } catch (IOException | RuntimeException e) {
            // No CloneTrust exists yet to delete the file on close.
            try {
                Files.deleteIfExists(file);
            } catch (IOException deleteFailure) {
                e.addSuppressed(deleteFailure);
            }
            throw e;
        }
        return new CloneTrust(file);
    }

    /** Writes the config file's content; tests substitute a writer that fails. */
    @FunctionalInterface
    interface ConfigWriter {
        void write(Path file, String content) throws IOException;
    }

    /**
     * A temporary global git config trusting one repository for local clones. Pass
     * {@link #environment()} to the process that clones; closing deletes the file.
     */
    public record CloneTrust(Path file) implements AutoCloseable {

        /** The environment that makes git read this file as its global config. */
        public Map<String, String> environment() {
            return Map.of("GIT_CONFIG_GLOBAL", file.toString());
        }

        @Override
        public void close() throws IOException {
            Files.deleteIfExists(file);
        }
    }

    /**
     * The paths git may report for {@code directory}: the path as given, made absolute, and
     * the real path when it differs. Git derives a worktree from getcwd, which resolves
     * symlinks (macOS reports /var/folders/... as /private/var/folders/...), and git 2.43,
     * the image's version, compares safe.directory values without normalizing them. Neither
     * path is normalized lexically: {@code link/../lake} opens the lake beside the link's
     * target, and dropping {@code link/..} would name a directory git never opens.
     */
    static List<String> names(Path directory) {
        Set<String> names = new LinkedHashSet<>();
        Path absolute = directory.toAbsolutePath();
        names.add(absolute.toString());
        try {
            names.add(absolute.toRealPath().toString());
        } catch (IOException e) {
            // Not created yet: git cannot run in it either, so the given path is enough.
        }
        return List.copyOf(names);
    }

    /**
     * The files git reads as the global config for buf's git processes, in git's order: the
     * file GIT_CONFIG_GLOBAL names, or else the XDG config and ~/.gitconfig. An empty value
     * counts as unset, as buf drops empty variables before it starts git.
     *
     * <p>A relative GIT_CONFIG_GLOBAL, HOME or XDG_CONFIG_HOME is refused. buf's client git
     * resolves it against a temporary directory buf picks for each run, which {@code ..} can
     * climb out of to a real config. The git serving the clone resolves it inside the lake's
     * .git, so it would read a file from a lake another user may own as global config. The
     * user's policy can be neither dropped nor reproduced here, so the check stops instead.
     *
     * @throws IOException naming each relative variable
     */
    static List<String> userGlobalConfigs(Map<String, String> env) throws IOException {
        List<String> relative = new ArrayList<>();
        for (String variable : List.of("GIT_CONFIG_GLOBAL", "XDG_CONFIG_HOME", "HOME")) {
            String value = env.get(variable);
            if (value != null && !value.isEmpty() && !Path.of(value).isAbsolute()) {
                relative.add(variable + " is '" + value + "'");
            }
        }
        if (!relative.isEmpty()) {
            throw new IOException("buf's breaking check needs absolute paths, but "
                + String.join(", ", relative) + ". buf's git would resolve a relative one against a"
                + " temporary directory, and the git serving the clone inside the lake's .git."
                + " Set each to an absolute path.");
        }
        List<String> configs = new ArrayList<>();
        String explicit = env.get("GIT_CONFIG_GLOBAL");
        if (explicit != null && !explicit.isEmpty()) {
            configs.add(explicit);
        } else {
            String home = env.get("HOME");
            String xdg = env.get("XDG_CONFIG_HOME");
            if (xdg != null && !xdg.isEmpty()) {
                configs.add(Path.of(xdg, "git", "config").toString());
            } else if (home != null && !home.isEmpty()) {
                configs.add(Path.of(home, ".config", "git", "config").toString());
            }
            if (home != null && !home.isEmpty()) {
                configs.add(Path.of(home, ".gitconfig").toString());
            }
        }
        return configs;
    }

    /** A git config value in double quotes, so spaces, '#', ';' and newlines survive. */
    private static String quote(String value) {
        return '"' + value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + '"';
    }
}
