package space.cohub.vdp.protolake.util.git;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Git's {@code safe.directory} trust for the lake repository protolake works in.
 *
 * <p>Git 2.35.2 and later refuse a repository whose directory belongs to another user
 * ("detected dubious ownership"). A lake commonly does: protolake runs as uid 1001 in its
 * image, while a bind-mounted lake belongs to the host user, and Docker Desktop's VirtioFS
 * reports a mount's root as owned by root. Protolake trusts exactly the repository it was
 * pointed at, never a wildcard, the same exception actions/checkout makes for its workspace.
 * The trust lives in protolake rather than in the wrapper script, so lakes generated by an
 * older wrapper are covered without regenerating it.
 */
public final class SafeDirectory {

    private SafeDirectory() {}

    /**
     * {@code -c safe.directory=<path>} arguments that make one git invocation trust
     * {@code repository}'s worktree. Command-line configuration reaches only that git
     * process, which is all a direct invocation needs.
     */
    public static List<String> configArgs(Path repository) {
        List<String> args = new ArrayList<>();
        for (String name : names(repository)) {
            args.add("-c");
            args.add("safe.directory=" + name);
        }
        return args;
    }

    /**
     * Writes a temporary global git config that trusts {@code repository}'s {@code .git}
     * directory, for tools that clone the repository locally (buf's {@code .git#ref=}
     * inputs). The image's git, Ubuntu's 2.43 with the CVE-2024-32004 patch (upstream
     * reverted it in 2.45.2), refuses to serve a local clone of a git directory another
     * user owns, and git strips command-line configuration from the serving process, so
     * the trust must come from a global config. The file includes the user's own global
     * config first, so their other settings still apply.
     */
    public static CloneTrust trustForLocalClone(Path repository) throws IOException {
        return trustForLocalClone(repository, userGlobalConfigs());
    }

    static CloneTrust trustForLocalClone(Path repository, List<String> userConfigs) throws IOException {
        StringBuilder config = new StringBuilder("[include]\n");
        for (String userConfig : userConfigs) {
            config.append("\tpath = ").append(quote(userConfig)).append('\n');
        }
        // After the include: an empty safe.directory in the user's config clears the
        // entries before it, and must not clear this one.
        config.append("[safe]\n");
        for (String name : names(repository)) {
            config.append("\tdirectory = ").append(quote(name + "/.git")).append('\n');
        }
        Path file = Files.createTempFile("protolake-git-", ".gitconfig");
        Files.writeString(file, config, StandardCharsets.UTF_8);
        return new CloneTrust(file);
    }

    /**
     * A temporary global git config trusting one repository for local clones. Pass
     * {@link #environment()} to the process that clones; closing deletes the file.
     */
    public record CloneTrust(Path file) implements AutoCloseable {

        /** The environment that makes git read this file as its global config. */
        public Map<String, String> environment() {
            return Map.of("GIT_CONFIG_GLOBAL", file.toString());
        }

        @Override
        public void close() throws IOException {
            Files.deleteIfExists(file);
        }
    }

    /**
     * The paths git may report for {@code directory}: the absolute path, and the real path
     * when it differs. Git derives a worktree from getcwd, which resolves symlinks (macOS
     * reports /var/folders/... as /private/var/folders/...), and git 2.43, the image's
     * version, compares safe.directory values without normalizing them.
     */
    static List<String> names(Path directory) {
        Set<String> names = new LinkedHashSet<>();
        Path absolute = directory.toAbsolutePath().normalize();
        names.add(absolute.toString());
        try {
            names.add(absolute.toRealPath().toString());
        } catch (IOException e) {
            // Not created yet: git cannot run in it either, so the absolute path is enough.
        }
        return List.copyOf(names);
    }

    /**
     * The files git reads as the global config when GIT_CONFIG_GLOBAL is unset, in git's
     * order, or the file GIT_CONFIG_GLOBAL already names. Git skips missing include files.
     * The paths are absolute: git dies on a {@code ~} include when HOME is unset, and
     * resolves a relative include against the including file's directory.
     */
    private static List<String> userGlobalConfigs() {
        String explicit = System.getenv("GIT_CONFIG_GLOBAL");
        if (explicit != null && !explicit.isEmpty()) {
            return List.of(Path.of(explicit).toAbsolutePath().toString());
        }
        List<String> configs = new ArrayList<>();
        String home = System.getenv("HOME");
        String xdg = System.getenv("XDG_CONFIG_HOME");
        if (xdg != null && !xdg.isEmpty()) {
            configs.add(Path.of(xdg, "git", "config").toString());
        } else if (home != null && !home.isEmpty()) {
            configs.add(Path.of(home, ".config", "git", "config").toString());
        }
        if (home != null && !home.isEmpty()) {
            configs.add(Path.of(home, ".gitconfig").toString());
        }
        return configs;
    }

    /** A git config value in double quotes, so spaces, '#', ';' and newlines survive. */
    private static String quote(String value) {
        return '"' + value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n") + '"';
    }
}
